### PR TITLE
Fast.ai documentation (tutorial notebooks)

### PR DESCRIPTION
**Pull request by hornof**
I added a section to the Luminide docs about how to run the fast.ai tutorial notebooks on Luminide.

Feel free to take a look via the GitHub repo (i.e. check out the code, build on your local machine, view in your local browser). Otherwise I'll just publish them to prod shortly and you can take a look there.

### CODE REVIEW

**Review by rgharris — APPROVED** [review]
Looks great! Short and sweet. Ran locally. 

Maybe mention that the auto detach should be adjusted if doing long training runs? Or can hold off as we will be fixing that soon.

**Comment by hornof** [comment]
> Maybe mention that the auto detach should be adjusted if doing long training runs?

Sure.

**Comment by hornof** [comment]
Also, I intentionally made it a short/simple as possible (initial version was more complete and detailed).  I want it look super easy to do -- especially compared to the other notebook servers, e.g. colab, Jarvis, Gradient.

**Review by anlthms — APPROVED** [review]
all look good to me. may be a good time to replace https://luminide.readthedocs.io/_images/feb-training-completed.png and https://luminide.readthedocs.io/_images/feb-full-sweep-graph.png...

**Pull request merged**
